language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: aivar.magi@partner.smit.ee
  password: Njc6ztkvz7s51!
  api: https://api.run.pivotal.io
  organization: aivar
  space: development
